services:
  scout-events-db:
    hostname: scount-events-db
    image: cockroachdb/cockroach:v23.1.17
    networks:
      - scout-events-net
    ports:
      - "26257:26257"
      - "8081:8080"
    command: start-single-node --insecure
    volumes:
      - ${PWD}/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - COCKROACH_DATABASE=scouting
      - COCKROACH_USER=liquibase
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 3s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:latest
    networks:
      - scout-events-net
    depends_on:
      scout-events-db:
        condition: service_healthy
    volumes:
      - ${PWD}/db/changelog:/liquibase/changelog
      - ${PWD}/db/properties:/liquibase/properties
    entrypoint: liquibase --logLevel=debug update --defaultsFile=/liquibase/properties/liquibase.properties

networks:
  scout-events-net:
    driver: bridge
