version: "3.5"

services:
  scout-events-db:
    image: cockroachdb/cockroach:v23.1.17
    ports:
      - "26257:26257"
      - "8081:8080"
    command: start-single-node --insecure
    volumes:
      - ${PWD}/cockroach-data/crdb:/cockroach/cockroach-data
      - ${PWD}/local/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - COCKROACH_DATABASE=scouting
      - COCKROACH_USER=liquibase
