# fly.toml app configuration file generated for troop77-events on 2025-04-24T07:34:15-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'troop77-events'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile'

[env]
DB_SSL_ROOT_CERT = '/root.crt'
LOG_LEVEL = 'info'

[http_service]
  internal_port = 8080
#  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = '10s'
  timeout = '2s'
  grace_period = '5s'
  method = 'get'
  path = '/healthcheck'
  protocol = 'http'
  tls_skip_verify = false

[[http_service.checks]]
  interval = '1m0s'
  timeout = '2s'
  grace_period = '5s'
  method = 'get'
  path = '/deepcheck'
  protocol = 'http'
  tls_skip_verify = false

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
