# fly.toml app configuration file generated for troop77-events on 2024-03-24T21:53:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'troop77-events'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  LOG_LEVEL = "info"
  DB_DATABASE = "scouting"

[[vm]]
  size = 'shared-cpu-1x'

[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/healthcheck"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false
  [services.http_checks.headers]

[[services.http_checks]]
  interval = "60s"
  grace_period = "5s"
  method = "get"
  path = "/deepcheck"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false
  [services.http_checks.headers]
