name: CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    uses: ./.github/workflows/verify-commit.yml

  dependency-submission:
    needs: build
    uses: ./.github/workflows/dependency-submission.yml

  package:
    needs: build
    uses: ./.github/workflows/package.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
