name: CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    uses: ./.github/workflows/verify-commit.yml

  dependency-submission:
    needs: build
    uses: ./.github/workflows/dependency-submission.yml

  package:
    needs: build
    uses: ./.github/workflows/package.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      LIQUIBASE_URL: ${{ secrets.LIQUIBASE_URL }}
      LIQUIBASE_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
      LIQUIBASE_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    secrets: inherit
