name: Deploy

on:
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  liquibase-schema-update:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/update@v4.27.0
        with:
          url: ${{ secrets.LIQUIBASE_URL }}
          username: ${{ secrets.LIQUIBASE_USERNAME }}
          password: ${{ secrets.LIQUIBASE_PASSWORD }}
          changelogFile: src/main/resources/db/changelog/changelog-root.yaml
          rollbackOnError: true
          showSummary: verbose

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1.5
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
