name: CI Verify Commit

on:
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Install playwright drivers
        run: go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps

      - name: Start containers
        run: |
          docker compose up -d
          sleep 10

      - name: Run application
        run: DB_HOSTNAME=localhost DB_NAME=scouting DB_PASSWORD=admin DB_PORT=26257 DB_USERNAME=admin go run main.go &

      - name: Run Tests
        run: go test -v ./...
